name: Clean scraped data

on: workflow_dispatch
#   push:
#     paths:
#       - '**.txt'

defaults:
  run:
    # set common working directory for all (tasks?) as the root repository directory
    working-directory: .

jobs:

  Cleaning:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run clean_data.py
        run: |
            python src/data/clean_data.py

      - name: Commit files
        run: |
          git config --global user.email "siti.sarah.a.hannes@gmail.com"
          git config --global user.name "Sarah Hannes"
          git pull
          git add .
          git commit -m "Clean scraped data using GH Action $(date)"
          git push --set-upstream origin dev
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
