name: Save to gDrive (shell only)
on: workflow_dispatch

defaults:
  run:
    # set common working directory for all (tasks?) as the root repository directory
    working-directory: .

jobs:
  Upload:
    name: Replace existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update permission
        run: 
          chmod +x ./.github/scripts/decrypt_secret_runPy.sh
        
      - name: Decrypt encrypted credentials
        run: ./.github/scripts/decrypt_secret_runPy.sh
        env:
          CLIENT_SECRET_PASSPHRASE: ${{ secrets.CLIENT_SECRET_PASSPHRASE }}