name: Overwrite gdrive file
on: workflow_dispatch

defaults:
  run:
    # set common working directory for all (tasks?) as the root repository directory
    working-directory: .

jobs:
  Upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt encrypted credentials
        run: ./.github/scripts/decrypt_secret.sh
        env:
          CLIENT_SECRET_PASSPHRASE: ${{ secrets.CLIENT_SECRET_PASSPHRASE }}
      - name: Test overwritting data.txt on Google Drive
        run: |
            python ./src/data/upload_to_gdrive.py
