name: Save to gDrive (shell & py)
on: workflow_dispatch

defaults:
  run:
    # set common working directory for all (tasks?) as the root repository directory
    working-directory: .

jobs:
  Upload:
    name: Replace existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
          pip install nest_asyncio
          pip install -U scikit-learn
          pip install -r requirements.txt
          pip install google-api-python-client
          pip install google-auth-oauthlib

      - name: Update permission
        run: 
          chmod +x ./.github/scripts/decrypt_secret.sh
        
      - name: Decrypt encrypted credentials
        run: ./.github/scripts/decrypt_secret.sh
        env:
          CLIENT_SECRET_PASSPHRASE: ${{ secrets.CLIENT_SECRET_PASSPHRASE }}

      - name: Test overwritting data.txt on Google Drive
        run: |
            python ./src/data/upload_to_gdrive.py