name: Scrape Hourly CLI
#on: workflow_dispatch # manual trigger (for now)
on:
  schedule:
    # Runs "at minute 0 every hour" (see https://crontab.guru)
    - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Scraping:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
            pip install nest_asyncio
            pip install -r requirements.txt

      - name: Scrape Hourly - CLI
        run: |
            twint -s dhl --since [DateTime]::Now.AddHours(-1).ToString('yyyy-MM-dd HH:mm:ss') -o scrape_cli.txt

      - name: Commit files
        run: |
          git config --global user.email "siti.sarah.a.hannes@gmail.com"
          git config --global user.name "Sarah Hannes"
          git pull
          git add .
          git commit -m "Scrape using GH Action $(date)"
          git push --set-upstream origin dev
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
