name: Save to gDrive (marketplace action)

on:
  workflow_dispatch:

jobs:
  Upload:
    name: Replace existing file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mkrakowitzer/actions-googledrive@master
        with:
          upload-from: file1.txt
          upload-to: IRL-L2-Support/platform-architecture-docs
          skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
          google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
